earnings <- c(30,100,20)
expences <- c(10,50,40)
bank <- (earnings - expences)
print(earnings * 3)
print(earnings / 10)
print(earnings - 30)
print(earnings + 100)
print(sum(bank))
print(sum(earnings) > sum(expences))
